import React from "react";
import axios from 'axios';
import {withRouter} from "react-router-dom";
import { connect } from 'react-redux';


class Inputfield extends React.Component {
  
  constructor(props) {
    super(props)
    this.state = {
      inputValue: "",
      courses: []
      
    }
    this.updateInputValue = this.updateInputValue.bind(this);
    this._handleKeyPress = this._handleKeyPress.bind(this);
    
  }

  updateInputValue(event) {
    this.setState({inputValue: event.target.value});
  }
  
  

  _handleKeyPress(e) {
    if (e.key === 'Enter') {
      console.log(this);
      e.preventDefault();
      //console.log(this);
      var querystring = require('querystring');
        var url = '/search?'+querystring.stringify({
            q: this.state.inputValue
        });
        //this.props.history.push(url);
      window.location.href= url;
      console.log(url);
      
      
    }
  }

  componentDidMount() {
     $(document).ready(function(){
      
          $('input.autocomplete').autocomplete({
                        data: {
           "AAS100 - Intro To Afric Amer Studies": null,
"AAS190 - Fresh Sem": null,
"AAS215 - Jazz": null,
"AAS247 - Racial & Ethnic Relations": null,
"AAS261 - Survey Af-Am Lit Before 1900": null,
"AAS285 - Special Topics in AAS": null,
"AAS288 - Black Women's Poetry": null,
"AAS303 - Black Music": null,
"AAS326 - Black Christian Thought": null,
"AAS334 - Contemporary African Politics": null,
"AAS385 - Topics in Afr Amer Studies": null,
"AAS385W - Topics in Afr Amer Studies": null,
"AAS387RW - GA Civil Rights Cold Cases": null,
"AAS398R - Directed Readings": null,
"AAS485 - Special Topics Seminar": null,
"AAS495A - Honors Research": null,
"AFS190 - Frsh Seminar": null,
"AFS263 - Intro to African Studies": null,
"AFS270 - Topic Seminar": null,
"AFS319 - Media,Islam,& Social Movements": null,
"AFS334 - Contemporary African Politics": null,
"AFS366W - Development Issues for Africa": null,
"AFS389 - Special Topics": null,
"AFS389W - Special Topics": null,
"AFS489W - Spec.Topics Sem.": null,
"AMST190 - Freshman Sem": null,
"AMST201W - Intro. to American Studies": null,
"AMST385 - Special Top": null,
"AMST387RW - GA Civil Rights Cold Cases": null,
"AMST489W - Adv Spec Topics American St": null,
"AMST490W - Senior Seminar": null,
"AMST495R - Honors Thesis": null,
"AMST495RW - Honors Thesis": null,
"AMST496R - Internship": null,
"AMST498R - Supervised Reading and Study": null,
"AMST499R - Senior Research": null,
"ANCMED101 - Intro to Anc't Med Societies": null,
"ANCMED190 - Freshmen Seminar": null,
"ANCMED202R - Literature & Traditions": null,
"ANT101 - Introduction to Anthropology": null,
"ANT190 - Freshman Seminar": null,
"ANT200 - Foundations of Behavior": null,
"ANT201 - Concepts & Meth in Biol Anth": null,
"ANT203 - Foundations of Linguistics": null,
"ANT205 - Foundations of Global Health": null,
"ANT207 - Foundation Development Studies": null,
"ANT250W - Today's World": null,
"ANT258 - Anthropology of the Jews": null,
"ANT280R - Anthro. Perspectives": null,
"ANT285 - Anthropology; Special Topics": null,
"ANT304W - Paleolithic Archaeology": null,
"ANT337 - Religion Health and Healing": null,
"ANT339 - Defining Health": null,
"ANT380 - Muslim Cultures and Politics": null,
"ANT385 - Special Topics": null,
"ANT386 - Special Topics": null,
"ANT495A - Honors Research I": null,
"ANT497R - Undergraduate Research": null,
"ARAB101 - Elementary Arabic I": null,
"ARAB201 - Intermediate Arabic I": null,
"ARAB301 - Advanced Arabic I": null,
"ARAB401W - Advanced - Plus Arabic": null,
"ARAB497R - Supervised Reading In Arabic": null,
"ARTHIST101 - Art/Arch Prehistory To Renaiss": null,
"ARTHIST103 - Understanding Architecture": null,
"ARTHIST190 - Freshman Seminar": null,
"ARTHIST210 - Introduction to Graphics & CAD": null,
"ARTHIST252 - European Painting, 1590-1700": null,
"ARTHIST265 - Europe in the 20th Century": null,
"ARTHIST289 - Perspect Non-West Art Topics": null,
"ARTHIST319R - Spec Stud": null,
"ARTHIST365 - Postcolonial African Art": null,
"ARTHIST369R - Spec Stud": null,
"ARTHIST373 - The Russian Avantgarde": null,
"ARTHIST387 - Conservatn/Cultrl Properties": null,
"ARTHIST389R - Spec Studi African Art Arch": null,
"ARTHIST393R - Special Studies History of Art": null,
"ARTHIST397R - Internship In History Of Art": null,
"ARTHIST398R - Supervised Reading & Research": null,
"ARTHIST475RW - Sem": null,
"ARTHIST485W - Sem": null,
"ARTHIST495RW - Honors": null,
"ARTVIS103 - Intro Drawing & Printmaking": null,
"ARTVIS105 - Intro Painting": null,
"ARTVIS109 - Intro Sculpture": null,
"ARTVIS111 - Foundations in Art Practices": null,
"ARTVIS398R - Directed Study": null,
"ARTVIS490 - Senior Seminar": null,
"BIOL120 - Concepts In Biology W/Lab": null,
"BIOL141 - Foundations of Modern Biol I": null,
"BIOL141L - Found. of Modern Biol I Lab": null,
"BIOL190 - Freshman Seminar": null,
"BIOL200 - Intro to Bio Research": null,
"BIOL205 - Compar Vertebrate Anat W/Lab": null,
"BIOL223 - Developmental Biology": null,
"BIOL240 - Organismal Form and Function": null,
"BIOL241 - Evolutionary Biology": null,
"BIOL247 - Ecology": null,
"BIOL247LW - Ecology Laboratory": null,
"BIOL250 - Cell Biology": null,
"BIOL264 - Genetics": null,
"BIOL285 - Special Topics in Biology": null,
"BIOL301 - Biochemistry I": null,
"BIOL320 - Animal Behavior": null,
"BIOL336 - Human Physiology": null,
"BIOL345 - Conservation Biology": null,
"BIOL352 - Epigenetics & Human Disease": null,
"BIOL360 - Introduction To Neurobiology": null,
"BIOL360L - Neurobiology Simulation Lab": null,
"BIOL370 - Introduction To Microbiology": null,
"BIOL370L - Intro to Microbiology Lab": null,
"BIOL385 - Special Topics in Biology": null,
"BIOL386 - Special Topics with Laboratory": null,
"BIOL434 - Physical Biology": null,
"BIOL441 - Molecular Biol & Evol Genetics": null,
"BIOL463 - Pop Biol & Evolutn Of Disease": null,
"BIOL485 - Special Topics in Biology": null,
"BIOL495A - Honors Research": null,
"BIOL495BW - Honors Research": null,
"BIOL497R - Supervised Reading": null,
"BIOL499R - Undergraduate Research": null,
"CBSC370A - Community Bldg & Soc Change I": null,
"CHEM150 - Structure and Properties": null,
"CHEM150L - Structure and Properties Lab": null,
"CHEM190 - Freshmen Seminar": null,
"CHEM221 - Organic Chemistry I": null,
"CHEM221L - Organic Chemistry Laboratory 1": null,
"CHEM221Z - Organic Chemistry I": null,
"CHEM226L - Organic Chemistry Lab I": null,
"CHEM260 - Quant Analytical Chemistry": null,
"CHEM260L - Analytical Chemistry Lab": null,
"CHEM300 - Phys Chem. for Life Sciences": null,
"CHEM301 - Biochemistry I": null,
"CHEM327 - Organometallic Chemistry": null,
"CHEM331 - Physical Chemistry I": null,
"CHEM331LW - Physical Chemistry Lab I": null,
"CHEM350 - Inorganic Chemistry": null,
"CHEM355L - Inorganic Chemistry Laboratory": null,
"CHEM392R - Chem Mentors": null,
"CHEM399R - Introduction To Research": null,
"CHEM495RW - Honors Thesis": null,
"CHEM497R - Supervised Reading": null,
"CHEM499R - Undergraduate Research": null,
"CHN101 - Elementary Chinese I": null,
"CHN103 - Elem Chn": null,
"CHN201 - Intermediate Chinese I": null,
"CHN235W - Chinese Writ. Systems in Asia": null,
"CHN271W - Mod China in Film and Fiction": null,
"CHN301 - Adv Chinese I": null,
"CHN303W - Adv. Chn.for Heritage Speakers": null,
"CHN373W - Confucian Classics": null,
"CHN375 - Topics in Chinese Studies": null,
"CHN388W - The Cultural Revolution": null,
"CHN401W - Adv Readings in Modern Chn I": null,
"CHN495A - Honors Chinese I": null,
"CL100 - Hero and Antihero": null,
"CL190 - Freshman Seminar": null,
"CL213 - Ancient Comedy": null,
"CL329R - Spec Stud in Classical Culture": null,
"CL495R - Honors Course": null,
"CL498R - Supervised Reading": null,
"CPLT190 - Fresh Sem": null,
"CPLT201W - Maj Texts": null,
"CPLT202W - Maj. Texts": null,
"CPLT203RW - Literatures Beyond the Canon": null,
"CPLT301 - Meth of Liter Interpretation": null,
"CPLT333 - Literature & Other Disciplines": null,
"CPLT389 - Special Topics": null,
"CPLT389W - Special Topics": null,
"CPLT490R - Lit. Proseminar for Majors": null,
"CPLT495RW - Honors Thesis": null,
"CPLT497R - Supervised Reading": null,
"CS153 - Computing for Bioinformatics": null,
"CS170 - Intro to Computer Science I": null,
"CS171 - Intro to Computer Science II": null,
"CS224 - Discrete Structures": null,
"CS255 - Comp Org/Assembly Programming": null,
"CS323 - Data Structures and Algorithms": null,
"CS325 - Artificial Intelligence": null,
"CS370 - Computer Science Practicum": null,
"CS377 - Database Systems": null,
"CS450 - Systems Programming": null,
"CS453 - Computer Security": null,
"CS456 - Compiler Construction": null,
"CS497R - Directed Study": null,
"DANC121R - Ballet I": null,
"DANC123R - Contemporary Modern Dance I": null,
"DANC124R - Jazz I (Introduction)": null,
"DANC127R - World Dance Forms": null,
"DANC150R - Movement Improvisation": null,
"DANC190 - Freshman Seminar": null,
"DANC207R - Emory Dance Company": null,
"DANC221R - Ballet II": null,
"DANC223R - Contemporary Modern Dance II": null,
"DANC224R - Jazz II (Beginn./Intermediate)": null,
"DANC226 - Topics in Somatic Practices": null,
"DANC230 - Principles of Design": null,
"DANC250 - Choreography I": null,
"DANC321R - Ballet III": null,
"DANC323R - Contemporary Modern Dance III": null,
"DANC324R - Jazz Dance III (Advanced)": null,
"DANC329 - Contemporary Issues in the Performing Arts": null,
"DANC329 - Contemp. Issues in Perf. Arts": null,
"DANC330 - Dance Pedagogy": null,
"DANC421R - Ballet IV": null,
"DANC423R - Contemporary Modern Dance IV": null,
"DANC491R - Special Projects": null,
"DANC492R - Spec Proj": null,
"DANC493R - Spec Proj": null,
"DANC494R - Special Projects": null,
"DANC495A - Honors Thesis": null,
"DANC495BW - Honors Thesis": null,
"DANC496R - Special": null,
"DANC497R - Special Projects": null,
"DANC499R - Spec Proj": null,
"DANC999XFR - Non-Equivalent Transfer Course": null,
"EAS235W - Chinese Writ. Systems in Asia": null,
"EAS250W - Intro to East Asian Studies": null,
"EAS271W - Mod China in Film and Fiction": null,
"EAS276 - Making of Modern Korea": null,
"EAS337 - Religion Health and Healing": null,
"EAS374W - Confucian Classics": null,
"EAS380 - Social Movement, East & West": null,
"EAS385 - Spec Top": null,
"EAS388W - The Cultural Revolution": null,
"ECON101 - Principles Of Microeconomics": null,
"ECON112 - Principles Of Macroeconomics": null,
"ECON190 - Freshman Seminar": null,
"ECON201 - Intermediate Microeconomics": null,
"ECON212 - Intermediate Macroeconomics": null,
"ECON215 - Stocks,Bonds&Financl Markets": null,
"ECON220 - Probab.& Stat. for Economists": null,
"ECON231 - Intro To Global Trade & Fin": null,
"ECON309W - Contemporary Economic Issues": null,
"ECON310 - Experimental Economics": null,
"ECON333 - Financial Economics": null,
"ECON341 - Business & Government": null,
"ECON366W - Development Issues for Africa": null,
"ECON372 - Health Care Markets": null,
"ECON400 - Managerial Economics": null,
"ECON405 - Industrial Organization": null,
"ECON411W - Money & Banking": null,
"ECON420 - Econometrics": null,
"ECON425 - Mathematical Economics": null,
"ECON430 - Economics of Labor Markets": null,
"ECON431 - International Trade": null,
"ECON432 - International Finance": null,
"ECON433W - Advanced Financial Markets": null,
"ECON449 - Economics Internship": null,
"ECON495BW - Honors Research": null,
"ECON496R - Tutorial in Economics": null,
"ECON496RW - Tutorial in Economics": null,
"ECS100 - Peer Mentoring and Leadership": null,
"ECS300R - Honor Council Practicum": null,
"ECS400R - Honor Council Adv. Practicum": null,
"ENG101 - Expository Writing": null,
"ENG123R - Communicative Grammar": null,
"ENG181 - Writing About Literature": null,
"ENG190 - Freshman Seminar": null,
"ENG201W - Multimedia Journalism": null,
"ENG202 - Writing Center Practicum": null,
"ENG205W - Poetry": null,
"ENG210W - Major Authors": null,
"ENG211W - Literature and the Arts": null,
"ENG215 - History of Drama and Theater I": null,
"ENG221RW - Advanced Writing Workshop": null,
"ENG223 - Rhetorical Grammar": null,
"ENG250W - Amer Lit": null,
"ENG255W - British Literature Before 1660": null,
"ENG302W - Technical Writing": null,
"ENG311RW - Shakespeare": null,
"ENG317W - Milton": null,
"ENG320W - Restoratn & Early 18th Cent.": null,
"ENG330W - Romanticism": null,
"ENG341W - 20th Century English Novel": null,
"ENG342RW - Modern Irish Literature": null,
"ENG345W - Post Colonial Literature": null,
"ENG348W - Contemporary Literature": null,
"ENG351 - American Literature": null,
"ENG356W - Native American Literature": null,
"ENG357W - Southern Literature": null,
"ENG363W - Discourse Analysis": null,
"ENG369 - Satire": null,
"ENG380 - Topics": null,
"ENG380W - Topic": null,
"ENG384RW - Criticism": null,
"ENG386 - Literature and Science": null,
"ENG389 - Special Topics": null,
"ENG389W - Special Topics": null,
"ENG399R - Independent Study": null,
"ENG482RW - Seminar in Fiction": null,
"ENG483R - Seminar in Criticism & Theory": null,
"ENG483RW - Seminar in Criticism & Theory": null,
"ENG489 - Special Top Adv Study": null,
"ENG490W - Sem in Literary Interpretation": null,
"ENG495RW - Honors Thesis": null,
"ENGCW190 - Freshman Sem": null,
"ENGCW271W - Introduction to Poetry Writing": null,
"ENGCW272W - Introduction to Fiction Writing": null,
"ENGCW370RW - Creative Wrt": null,
"ENGCW371RW - Creative Wrt": null,
"ENGCW372RW - Intermediate Playwriting": null,
"ENGCW376RW - Creativ Wrt": null,
"ENGCW378RW - Screenwriting": null,
"ENGCW385RW - GA Civil Rights Cold Cases": null,
"ENGCW397RW - Creative Writing": null,
"ENGCW495RW - Creative Writing Honors": null,
"ENVS120 - Living in the Anthropocene": null,
"ENVS130 - Environmental Sciences": null,
"ENVS131 - Intro.to ENVS Field Studies": null,
"ENVS190 - Fresh Sem": null,
"ENVS222 - Evolutn of the Earth with Lab": null,
"ENVS227 - Environmental Policy": null,
"ENVS232 - Fundamentals of Ecology w/Lab": null,
"ENVS234 - Biophilic and Green Design": null,
"ENVS247 - Ecology": null,
"ENVS247LW - Ecology Laboratory": null,
"ENVS250 - Fundam. of Cartography & GIS": null,
"ENVS299R - Fundamentals of ENVS Rsrch": null,
"ENVS321 - Geology and Human Health": null,
"ENVS324 - Environmental Economics": null,
"ENVS326 - Climate Change and Society": null,
"ENVS344 - American Environmental History": null,
"ENVS345 - Conservation Biology": null,
"ENVS359 - Ecology & Evolution of Disease": null,
"ENVS370A - Community Bldg & Soc Change I": null,
"ENVS390R - Sem On Environmental Issues": null,
"ENVS399R - Intro to Independent Research": null,
"ENVS426 - U.N.Climate Change Conference": null,
"ENVS494RW - Individual Research in ENVS": null,
"ENVS495A - Honors Research": null,
"ENVS497R - Undergraduate Internship": null,
"ENVS498R - Individual Directed Reading": null,
"FILM106 - Photography I": null,
"FILM107 - Intro to Digital Video": null,
"FILM190 - Freshmen Seminar": null,
"FILM204 - Introduction to Media Studies": null,
"FILM206R - Photography II": null,
"FILM208 - Digital Media & Culture": null,
"FILM270 - Introduction To Film": null,
"FILM300R - Filmmaking Practicum": null,
"FILM319 - Media,Islam,& Social Movements": null,
"FILM371 - History Of Film To 1954": null,
"FILM373 - Special Topics in Film": null,
"FILM375 - The Russian Avantgarde": null,
"FILM378RW - Screenwriting": null,
"FILM381W - Classical Film Theory": null,
"FILM385 - Documentary Filmmaking I": null,
"FILM389W - Special Topics in Media": null,
"FILM390 - Children & Media": null,
"FILM391R - Studies in Major Figures": null,
"FILM393 - Documentary Film & Media Hist": null,
"FILM399 - Internship/Filmmaking Projects": null,
"FILM403 - The Biz": null,
"FILM404 - Gender in Film and Media": null,
"FILM495R - Honors Thesis": null,
"FILM499R - Directed Research": null,
"FREN101 - Elementary French I": null,
"FREN102 - Elementary French II": null,
"FREN201 - Intermediate French": null,
"FREN203 - Advanced French": null,
"FREN210 - Fren For Reading Comprehension": null,
"FREN310W - Writing Skills": null,
"FREN313 - French and Francophone Culture": null,
"FREN314 - What Is Interpretation?": null,
"FREN331 - Temporalities": null,
"FREN341 - Intersections": null,
"FREN488 - Topics in French": null,
"FREN488W - Topics in French": null,
"FREN495A - Honors": null,
"FREN497R - Individual Directed Research": null,
"GER101 - Elementary German I": null,
"GER190 - Freshman Seminar": null,
"GER192R - Beginning Conversation": null,
"GER201 - Intermediate German I": null,
"GER230 - Yiddish Culture": null,
"GER301 - German Studies I": null,
"GER320 - Business German I": null,
"GER360 - Current German Issues": null,
"GER375 - Spec. Topics in German Studies": null,
"GER375W - Spec. Topics in German Studies": null,
"GER385 - Topics in German Linguistics": null,
"GER392R - German Conversation": null,
"GER470W - Topics": null,
"GER495A - Honors": null,
"GRK101 - Elementary Greek I": null,
"GRK201 - Intermediate Greek": null,
"GRK312 - Tragedy": null,
"GRK495RW - Honors": null,
"GRK498R - Supervised Reading": null,
"HEBR101 - Elementary Modern Hebrew I": null,
"HEBR201 - Intermediate Modern Hebrew I": null,
"HEBR301 - Advanced Modern Hebrew I": null,
"HEBR435R - Hebrew of the Israeli Media": null,
"HEBR497R - Supervised Reading": null,
"HIST150 - Great Books": null,
"HIST185 - Spec Topics": null,
"HIST190 - Freshman Seminar": null,
"HIST201 - Formation of European Society": null,
"HIST231 - Found of Amer Society to 1877": null,
"HIST241W - Topics in History and Text": null,
"HIST285 - Topics": null,
"HIST285W - Topics": null,
"HIST304 - Emperors, Barbarians, & Monks": null,
"HIST308 - Revolutionary France,1750-1815": null,
"HIST329 - American Jewish History": null,
"HIST344 - American Environmental History": null,
"HIST360 - Mexico": null,
"HIST385 - Spec Topics": null,
"HIST385W - Spec Topics": null,
"HIST387RW - GA Civil Rights Cold Cases": null,
"HIST487RW - Jr/Sr Colloquium": null,
"HIST488RW - Jr./Sr. Colloquium": null,
"HIST489RW - Jr/Sr Coll": null,
"HIST494R - History Internship": null,
"HIST495A - Intro Historcl Interpret I": null,
"HIST498R - Supervised Reading": null,
"HLTH100 - It's Your Health": null,
"HLTH190 - Freshman Seminar Human Health": null,
"HLTH207 - Fundamentals of Epidemiology": null,
"HLTH220 - Intro.to Nutrition Science": null,
"HLTH230 - Health and Humanities": null,
"HLTH250 - Foundations of Global Health": null,
"HLTH300R - Peer Health Partners": null,
"HLTH310 - Defining Health": null,
"HLTH320 - Nutrition and Chronic Disease": null,
"HLTH331 - Disability & Bioethics": null,
"HLTH332 - Health & Human Rights": null,
"HLTH350R - Core Issues in Global Health": null,
"HLTH351 - Exporting Mental Health": null,
"HLTH385 - Special Topics": null,
"HLTH397R - Directed Reading": null,
"HLTH399R - Directed Research": null,
"HLTH440 - Botanical Medicine & Health": null,
"HLTH485 - Variable Topics Human Health": null,
"HLTH495A - Honors Research": null,
"HLTH497R - Independent Reading": null,
"HLTH499R - Independent Research": null,
"HNDI101 - Elementary Hindi I": null,
"HNDI201 - Intermediate Hindi I": null,
"HNDI410R - Advanced Language and Culture": null,
"HNDI497R - Directed Study": null,
"IDS190 - Fresh Sem": null,
"IDS200W - Interdisciplinary Foundations": null,
"IDS204 - Introduction to Media Studies": null,
"IDS206 - Foundations of Sustainability": null,
"IDS207 - Foundation Development Studies": null,
"IDS216W - Visual Culture": null,
"IDS220R - ORDER Seminar": null,
"IDS220RW - ORDER Seminar": null,
"IDS263 - Intro to African Studies": null,
"IDS285 - Intro.Interdisciplinary Topics": null,
"IDS290 - Interdisciplinary Sidecar": null,
"IDS385 - Special Topics": null,
"IDS385W - Special Topics": null,
"IDS485R - Internship for IDS": null,
"IDS490R - Supervised Reading and Study": null,
"IDS491W - Senior Seminar": null,
"IDS495RW - Honors": null,
"IDS499R - Senior Research": null,
"ITAL101 - Language & Culture, Elem I": null,
"ITAL201 - Language & Culture, Inter. I": null,
"ITAL301W - Language & Culture, Adv. I": null,
"ITAL375 - Tops in Ital Lit in Trans": null,
"ITAL376 - Top in Italian Cultr in Trans": null,
"ITAL397R - Supervised Reading": null,
"ITAL470 - Topics in Italian Literature": null,
"JPN101 - Elementary Japanese I": null,
"JPN201 - Intermediate Japanese I": null,
"JPN234 - Intro to Japanese Linguistics": null,
"JPN301 - Adv Conversation & Composition": null,
"JPN375 - Topics in Jpn Studies": null,
"JPN375W - Topics in Jpn Studies": null,
"JPN401 - Adv Lang & Cultural Studies I": null,
"JS125 - Intro To Jewish Literature": null,
"JS185 - Topics in Jewish Studies": null,
"JS190 - Freshman Seminar": null,
"JS230 - Yiddish Culture": null,
"JS250 - Archaeology and The Bible": null,
"JS258 - Anthropology of the Jews": null,
"JS271 - Topics in Jewish History": null,
"JS273 - Topics in Jewish Rel & Culture": null,
"JS309 - Jews & Judaism in Modern Times": null,
"JS329 - American Jewish History": null,
"JS348W - Israeli-Palestinian Literature": null,
"JS370 - Topics in Jewish Relig & Culture": null,
"JS370 - Topics in Jewish Relig&Culture": null,
"JS370W - Topics in Jewish Relig&Culture": null,
"JS371 - Topics in Jewish History": null,
"JS435R - Hebrew of the Israeli Media": null,
"JS495RW - Honors Thesis": null,
"JS497R - Dir Reading In Jewish Studies": null,
"KRN101 - Elementary Korean I": null,
"KRN102 - Elementary Korean II": null,
"KRN201 - Intermediate Korean I": null,
"KRN270 - Making of Modern Korea": null,
"KRN301 - Advanced Korean I": null,
"KRN372 - Social Movement, East & West": null,
"KRN389 - Special Topics": null,
"KRN401 - Language & Culture of Korea I": null,
"KRN403 - Korean for Profess. Purposes": null,
"LACS101 - Intro To Lat American Studies": null,
"LACS263W - Plantation to Postcolonial": null,
"LACS490R - Adv.Sem": null,
"LACS490RW - Adv Sem": null,
"LAT101 - Elementary Latin I": null,
"LAT201 - Intermediate Latin": null,
"LAT370 - Ovid's Love Poems & Heroides": null,
"LAT495R - Honors": null,
"LAT498R - Supervised Reading": null,
"LING190 - Fresh Sem": null,
"LING201 - Foundations of Linguistics": null,
"LING212W - Structure of Human Language": null,
"LING234 - Intro to Japanese Linguistics": null,
"LING235W - Chinese Writ. Systems in Asia": null,
"LING242 - Languages of the World": null,
"LING303 - Phonetics": null,
"LING304 - Intro. to Spanish Linguistics": null,
"LING309 - Brain and Language": null,
"LING350 - Health Communication": null,
"LING385 - Special Topics in Linguistics": null,
"LING446W - Big/Small Data & Visualization": null,
"LING485W - Advanced Topics in Linguistics": null,
"LING495A - Honors Directed Research": null,
"LING497R - Directed Study": null,
"LING499R - Directed Research": null,
"MATH111 - Calculus I": null,
"MATH112 - Calculus II": null,
"MATH112Z - Calculus II": null,
"MATH116 - Life Sciences Calculus II": null,
"MATH211 - Adv Calculus (Multivariable)": null,
"MATH212 - Differential Equations": null,
"MATH221 - Linear Algebra": null,
"MATH250 - Foundations of Mathematics": null,
"MATH275 - Honors Linear Algebra": null,
"MATH315 - Numerical Analysis": null,
"MATH318 - Complex Variables": null,
"MATH328 - Number Theory": null,
"MATH346 - Intro To Optimization Theory": null,
"MATH351 - Partial Differential Equations": null,
"MATH361 - Probability & Statistics, I": null,
"MATH385 - Topics in Mathematics": null,
"MATH411 - Real Analysis I": null,
"MATH421 - Abstract Algebra I": null,
"MATH425 - Mathematical Economics": null,
"MATH495RW - Honors": null,
"MATH497R - Directed Study": null,
"MESAS100 - Intro to Middle Eastern Civs.": null,
"MESAS102 - Intro to S. Asian Civilizatns": null,
"MESAS125 - Intro To Jewish Literature": null,
"MESAS160 - Sacred Texts of MESAS": null,
"MESAS190 - Freshmen Seminar in MESAS": null,
"MESAS240 - Conversational Tibetan": null,
"MESAS250 - Archaeology and The Bible": null,
"MESAS270 - Special Topics MESAS-200 Level": null,
"MESAS300W - Beyond Borders": null,
"MESAS315W - The Qur'an": null,
"MESAS319 - Media,Islam,& Social Movements": null,
"MESAS330 - Tibetan Culture": null,
"MESAS348W - Israeli-Palestinian Literature": null,
"MESAS370 - Special Topics MESAS-300 Level": null,
"MESAS370W - Special Topics MESAS-300 Level": null,
"MESAS430W - Gender, Sexuality, Islam": null,
"MESAS495R - Honors Seminar in MESAS": null,
"MESAS497R - Directed Study": null,
"MUS110 - Masterworks of Western Music": null,
"MUS114 - Intro Theory & Composition": null,
"MUS121 - Theory & Analysis I W/Lab": null,
"MUS190 - Fresh Sem": null,
"MUS200 - Music, Culture and Society": null,
"MUS203 - Introduction to Opera": null,
"MUS215 - Jazz": null,
"MUS221 - Theory & Analysis III W/Lab": null,
"MUS230R - Media Composition": null,
"MUS240 - Jazz Improvisation": null,
"MUS270 - Special Topics in Music": null,
"MUS280 - Early Music Explorations": null,
"MUS283 - 19th Century Music": null,
"MUS300R - Ensemble": null,
"MUS303 - Black Music": null,
"MUS310R - Applied Music, Non-Majors": null,
"MUS320R - Applied Music": null,
"MUS347 - Elec Music/Midi Technology": null,
"MUS349R - Composition": null,
"MUS356W - Women, Music and Culture": null,
"MUS381W - Music and Storytelling": null,
"MUS440 - Diction for Singers I": null,
"MUS443R - Performance Techniques": null,
"MUS464W - Studies in Music Theory": null,
"MUS495A - Honors": null,
"MUS497R - Supervised Reading": null,
"NBB120 - From Botox to Behavior": null,
"NBB190 - Fresh Sem": null,
"NBB201 - Foundations of Behavior": null,
"NBB301 - Introduction To Neurobiology": null,
"NBB301L - Neurobiology Simulation Lab": null,
"NBB302 - Behavioral Neuroscience": null,
"NBB370 - Special Topics in NBB": null,
"NBB370W - Special Topics in NBB": null,
"NBB399R - Intro. to Mentored Research": null,
"NBB401W - Perspect.in Neuro.& Behavior": null,
"NBB482R - Frontiers in Neuroscience": null,
"NBB490 - Clinical Neurology Study": null,
"NBB495A - Honors Research": null,
"NBB495BW - Honors Research": null,
"NBB497W - Supervised Writing": null,
"NBB498R - Supervised Reading": null,
"NBB499R - Undergraduate Research": null,
"NRSG101 - Intro.to Professional Nursing": null,
"NRSG200 - Human Growth and Development": null,
"NRSG201 - Human Anatomy and Physiology I": null,
"NRSG202 - Human Anatomy & Physiology II": null,
"NRSG204 - Introductory Biostatistics": null,
"NRSG205 - Fundamentals of Microbiology": null,
"NRSG309 - Soc.Responsibility & Bioethics": null,
"NRSG310 - Pathophysiology for Nurses": null,
"NRSG312 - Foundations of Nurs.Practice": null,
"NRSG314 - Clinical Practicum": null,
"NRSG320 - Pharmacology for Nurses": null,
"NRSG322 - Health Promotion and Wellness": null,
"NRSG326 - Acute and Chronic Care": null,
"NRSG327 - Clinical Practicum II": null,
"NRSG328 - Pediatric Nursing": null,
"NRSG330 - Clinical Integration": null,
"NRSG331 - Honors Seminar": null,
"NRSG400 - Cardiac Dys&ECG Interpt Adults": null,
"NRSG401 - Forensic Nursing": null,
"NRSG402 - Introduction to Critical Care": null,
"NRSG404 - Research Residency": null,
"NRSG405 - Rural Health": null,
"NRSG406 - Emergency Nursing": null,
"NRSG408 - Maternity & Reprod.Hlth.Nrsg.": null,
"NRSG409 - Clinical Practicum III": null,
"NRSG411 - Mental Health Nursing": null,
"NRSG416 - Perspectives in Prof. Nursing": null,
"NRSG417 - Leadership, Advocacy & Policy": null,
"NRSG422 - Palliative Care/Meaningful Con": null,
"NRSG424 - Case Study Analysis Seminar II": null,
"NRSG425 - Becoming a Professional Nurse": null,
"NRSG430 - Nrsg.in Complex Care Situation": null,
"NRSG431 - Clinical Practicum IV": null,
"NRSG432 - Ambulatory Care": null,
"NRSG453 - Honors Thesis I": null,
"OISP990A - Academic Study Abroad Course": null,
"OISP991A - Academic Study Abroad Course": null,
"OISP992A - Academic Study Abroad Course": null,
"OISP993A - Academic Study Abroad Course": null,
"OISP994A - Academic Study Abroad Course": null,
"OISP995A - Academic Study Abroad Course": null,
"PACE101 - Pre-major Advising Connection": null,
"PACE201 - Pre-Major Advise Transfer Stud": null,
"PE110 - PPF/Aerobic Conditioning": null,
"PE112 - PPF/Swimming": null,
"PE114 - PPF/Jogging": null,
"PE116 - PPF/Indoor Cycling": null,
"PE126 - PPF/Cardio Tennis": null,
"PE128 - PPF/Weight Training for Women": null,
"PE130 - PPF/Aerobic Resistanc Training": null,
"PE132 - PPF/Free Weights Training": null,
"PE134 - PPF Weight/Resistance Training": null,
"PE135 - PPF - Intro. to Fitness Yoga": null,
"PE150 - Beginning Swimming": null,
"PE151 - Beginning Scuba Diving": null,
"PE160 - Martial Arts - General": null,
"PE162 - Boxing": null,
"PE164 - Tai Chi Chuan": null,
"PE167 - Beginning Yoga": null,
"PE172 - Beginning Racquetball": null,
"PE173 - Beginning Tennis": null,
"PE180 - Sports Officiating": null,
"PE184R - Indoor Climbing/Crosstraining": null,
"PE185 - PPF/Special Topics": null,
"PE187 - Indoor Soccer": null,
"PE191 - Social Dance": null,
"PE192 - Beginning Fencing": null,
"PE193 - Holistic Wellness": null,
"PE195 - Personal Self Defense (Women)": null,
"PE198 - Weights - All Levels": null,
"PE199 - Beginning Golf": null,
"PE212 - Conditioning/Swimming": null,
"PE214 - Functional Fitness and Running": null,
"PE232 - Conditioning/Indoor Cycling": null,
"PE235 - Fitness Yoga": null,
"PE236 - Circuit Training": null,
"PE285 - Special Topics in PE": null,
"PE296 - Spec Topics in Outdoor Educ.": null,
"PE399R - Adaptive Physical Education": null,
"PE401R - PPF": null,
"PE403R - PPF": null,
"PE404R - PPF": null,
"PE410R - PPF": null,
"PERS101 - Elementary Persian I": null,
"PERS201 - Intermediate Persian I": null,
"PERS301 - Advanced Persian I": null,
"PERS497R - Directed Study": null,
"PHIL100 - Basic Problems in Philosophy": null,
"PHIL110 - Introduction to Logic": null,
"PHIL111 - Existentialism & European Phil": null,
"PHIL112 - Pragmatism & American Phil": null,
"PHIL113 - Intro to Asian Philosophy": null,
"PHIL115 - Introduction to Ethics": null,
"PHIL116 - Intro to Bioethics": null,
"PHIL117 - Nature/Envrnmnt/Sustainability": null,
"PHIL118 - Intro to Business Ethics": null,
"PHIL119 - Contemporary Moral Issues": null,
"PHIL120 - Intro Social & Political Phil": null,
"PHIL121 - Intro to Philosophy of Law": null,
"PHIL122 - Intro Phil of Social Science": null,
"PHIL123 - Intro to Feminist Philosophy": null,
"PHIL127 - Belief, Knowledge & Truth": null,
"PHIL133 - Intro to Philosophy of Film": null,
"PHIL134 - Intro to Phil of Human Nature": null,
"PHIL136 - Love & Friendship": null,
"PHIL190 - Fresh Sem": null,
"PHIL200W - Ancient Greek & Medieval Phil": null,
"PHIL202W - Renaissance &Modern Philosophy": null,
"PHIL204W - 19th & 20th Century Philosophy": null,
"PHIL385 - Special Topics in Philosophy": null,
"PHIL406 - Topics Contemporary Philosophy": null,
"PHIL413 - Asian Philosophy": null,
"PHIL480R - Sem on Individual Philosophers": null,
"PHIL490R - Senior Seminar": null,
"PHIL495A - Honors (Directed Reading)": null,
"PHIL495B - Honors (Directed Reading)": null,
"PHIL495BW - Honors (Directed Reading)": null,
"PHIL497R - Directed Reading": null,
"PHYS115 - Intro Astronomy": null,
"PHYS116 - Intro Astronomy W/Lab": null,
"PHYS131 - Major Advances in Modern Phys.": null,
"PHYS141 - Intro Physics I W/Lab": null,
"PHYS151 - Phys for Sci & Engin I w/Lab": null,
"PHYS190 - Fresh Sem": null,
"PHYS220 - Math Methods for Sci & Engin": null,
"PHYS234 - Digital Elec/Microprocessors": null,
"PHYS253 - Modern Physics With Laboratory": null,
"PHYS365 - Electricity and Magnetism": null,
"PHYS380 - Special Topics in Physics": null,
"PHYS397R - Directed Study": null,
"PHYS434 - Physical Biology": null,
"PHYS444W - Adv Undergraduate Laboratory": null,
"PHYS495R - Honors Research": null,
"PHYS495RW - Honors Research": null,
"PHYS499R - Undergraduate Research": null,
"POLS100 - Natl Politics/United States": null,
"POLS110 - Intro to Intl Politics": null,
"POLS120 - Intro to Comparative Politics": null,
"POLS150 - Foundations of Amer. Democracy": null,
"POLS190 - Fresh Sem": null,
"POLS201 - Classical Political Thought": null,
"POLS202 - Modern Political Thought": null,
"POLS208 - Research Design and Methods": null,
"POLS227 - Environmental Policy": null,
"POLS310W - Research": null,
"POLS317 - Global Human Rights": null,
"POLS334 - Contemporary African Politics": null,
"POLS337 - Islam and Politics": null,
"POLS348 - Research": null,
"POLS351 - United States Supreme Court": null,
"POLS352 - Constitutional Law": null,
"POLS360 - Public Policy": null,
"POLS362 - Executive Branch Governance": null,
"POLS367 - Urban Politics": null,
"POLS370A - Community Bldg & Soc Change I": null,
"POLS385 - Spec. Topics": null,
"POLS385W - Spec Tops": null,
"POLS387R - Independent Research (CLSS)": null,
"POLS394 - Rsch.Topics Political Science": null,
"POLS394W - Rsch.Topics Political Science": null,
"POLS486 - Washington Semester": null,
"POLS487 - Internt'l Studies at Bard (NY)": null,
"POLS490R - Advanced Seminar": null,
"POLS490RW - Advanced Seminar": null,
"POLS494W - Rsch Topics Sem Polit Science": null,
"POLS495W - Research": null,
"POLS496RW - Internshp in Political Science": null,
"POLS497R - Directed Study": null,
"POLS497RW - Directed Study": null,
"PORT101 - Elementary Portuguese I": null,
"PORT110 - Portuguese for Span Speakers": null,
"PORT201 - Intermediate Portuguese I": null,
"PORT202 - Intermediate Portuguese II": null,
"PORT300W - Brazilian Texts and Cultures": null,
"PORT412 - Topics in Lusophone Culture": null,
"PORT495R - Honors Thesis": null,
"PORT497R - Supervised Reading": null,
"PSYC110 - Intro Psyc I": null,
"PSYC111 - Intro To Psyc II": null,
"PSYC190 - Fresh Sem": null,
"PSYC200W - Lab In Experimental Methods": null,
"PSYC205 - Child Development": null,
"PSYC210 - Adult Abnormal Behavior": null,
"PSYC211 - Childhood Psychopathology": null,
"PSYC212 - Social Psychology": null,
"PSYC302 - Human Learning & Memory": null,
"PSYC309 - Brain and Language": null,
"PSYC310 - Cognitive Development": null,
"PSYC311 - Adolescent Psychology": null,
"PSYC313 - Neuropsychology": null,
"PSYC315 - Psych. of Family Relationships": null,
"PSYC320 - Animal Behavior": null,
"PSYC323 - Drugs & Behavior": null,
"PSYC330 - Personality Theories": null,
"PSYC353 - Behavioral Neuroscience": null,
"PSYC385 - Special Topics in Psychology": null,
"PSYC410 - Sci & Pseudoscience In Psyc": null,
"PSYC473 - Adv Topics In Abn Psychology": null,
"PSYC495A - Honors Program": null,
"PSYC498R - Directed Reading": null,
"PSYC499R - Directed Research": null,
"QTM100 - Intro to Stat Inference": null,
"QTM110 - Intro.to Scientific Methods": null,
"QTM120 - Math.for Quantitative Sciences": null,
"QTM150 - Intro.to Stat.Computing I": null,
"QTM210 - Probability and Statistics": null,
"QTM220 - Regression Analysis": null,
"QTM285 - Topics in Quantitative Science": null,
"QTM302W - Technical Writing": null,
"QTM385 - Special Topics": null,
"QTM398R - Peer Mentoring in Statistics": null,
"QTM446W - Big/Small Data & Visualization": null,
"QTM497R - Directed Study": null,
"REES495A - Honors Program in REES": null,
"REL100R - Introduction to Religion": null,
"REL170 - Special Topics in Religion": null,
"REL190 - Fresh Sem": null,
"REL209 - Hist of Religions In America": null,
"REL210RW - Classic Religious Texts": null,
"REL212 - Asian Religious Traditions": null,
"REL260 - Archaeology and The Bible": null,
"REL270 - Special Topics in Religion": null,
"REL300 - Interpreting Religion": null,
"REL307 - East Asian Buddhism": null,
"REL309 - Jews & Judaism in Modern Times": null,
"REL315W - The Qur'an": null,
"REL322 - Religion & Sexuality": null,
"REL326 - Black Christian Thought": null,
"REL330 - Tibetan Culture": null,
"REL351W - Paul and his Letters": null,
"REL354R - Ethics": null,
"REL354RW - Ethics": null,
"REL358R - Religion and Healing": null,
"REL370 - Special Topics in Religion": null,
"REL374W - Confucian Classics": null,
"REL388W - The Cultural Revolution": null,
"REL472 - Topics in Religion": null,
"REL472W - Topics in Religion": null,
"REL495R - Directed Reading (Honors)": null,
"REL497R - Directed Reading": null,
"RUSS101 - Elementary Russian I": null,
"RUSS190 - Fresh Seminar": null,
"RUSS201 - Inter Russ Conversatn/Reading": null,
"RUSS301 - Adv Oral/Written Comm I": null,
"RUSS372W - Russia & the Age of Revolution": null,
"RUSS373 - The Russian Avantgarde": null,
"RUSS375 - Special Topics": null,
"SIRE299R - SIRE Research Partner Program": null,
"SOC101 - Intro to General Sociology": null,
"SOC190 - Fresh Sem": null,
"SOC221 - Culture and Society": null,
"SOC225 - Sociology of Sex and Gender": null,
"SOC230 - Sociolog Aspect Health/Illness": null,
"SOC245 - Individual & Society": null,
"SOC247 - Racial & Ethnic Relations": null,
"SOC289 - Special Topics in Sociology": null,
"SOC348 - Aging in Society": null,
"SOC352 - Happiness": null,
"SOC355W - Social Research I": null,
"SOC370A - Community Bldg & Soc Change I": null,
"SOC372 - Social Movement, East & West": null,
"SOC389 - Spec. Tops in Sociology": null,
"SOC446W - Big/Small Data & Visualization": null,
"SOC457W - Devlpmnt Sociological Theory": null,
"SOC494RW - Internship in Sociology": null,
"SOC495A - Honors": null,
"SOC497R - Directed Research": null,
"SOC498R - Supervised Reading": null,
"SOC499R - Independent Research": null,
"SPAN101 - Elementary Spanish I": null,
"SPAN190 - Freshman Seminar": null,
"SPAN201 - Intermediate Spanish I": null,
"SPAN212 - Intro to Hisp Texts & Contexts": null,
"SPAN300 - Intro to Hisp Cultural History": null,
"SPAN301W - Early Hisp. Texts & Contexts": null,
"SPAN302W - Modern Hisp Texts & Contexts": null,
"SPAN303 - Phonetics": null,
"SPAN304 - Intro. to Spanish Linguistics": null,
"SPAN312 - Theater, Film & Performance Art": null,
"SPAN318W - Critical Wrtng Hispanic Topics": null,
"SPAN385 - Topics in Language and Culture": null,
"SPAN410 - Topics in Spanish Linguistics": null,
"SPAN410W - Topics in Spanish Linguistics": null,
"SPAN412 - Topics in Hispanic Culture": null,
"SPAN460 - Topic": null,
"SPAN460W - Topic": null,
"SPAN495A - Honors": null,
"TBT101 - Elementary Tibetan I": null,
"THEA100 - Introduction to the Theater": null,
"THEA120 - Acting": null,
"THEA130 - Stagecraft": null,
"THEA190 - Fresh Seminar": null,
"THEA200R - Theatre Practicum": null,
"THEA210W - Reading for Performance": null,
"THEA215 - History of Drama and Theater I": null,
"THEA221 - Acting": null,
"THEA223 - Voice & Diction": null,
"THEA224 - Movement for the Actor": null,
"THEA230 - Principles of Design": null,
"THEA250 - Directing I": null,
"THEA260R - Ensemble": null,
"THEA300R - Production Assistantship": null,
"THEA317R - Studies in a Major Figure": null,
"THEA320R - Acting Laboratory": null,
"THEA329 - Contemp. Issues in Perf. Arts": null,
"THEA330R - Stagecraft Laboratory": null,
"THEA332 - Set Design": null,
"THEA333 - Lighting Design": null,
"THEA335 - Scenic Painting": null,
"THEA372RW - Intermediate Playwriting": null,
"THEA389 - Special Topics": null,
"THEA410W - Aesthetics and Criticism": null,
"THEA489 - Advanced Special Topics": null,
"WGS100W - Gender Trouble": null,
"WGS190 - Fresh Sem": null,
"WGS200 - Introduction to WGSS": null,
"WGS231 - Sociology of Sex and Gender": null,
"WGS285 - Variable Topics in WGSS": null,
"WGS316 - Politics-Recognition-Exclusion": null,
"WGS356W - Women, Music and Culture": null,
"WGS385 - Spec Topics": null,
"WGS385W - Spec Topics": null,
"WGS475RW - Advanced Seminar": null,
"WGS490RW - Senior Sem in WGSS": null,
"WGS495RW - Honors Research": null,
"WGS497R - Dir Reading in WGSS": null,
"WGS499R - Directed Research in WGSS": null,
"AAS239W - Hist.of Afric.Amer. Since 1865": null,
"AAS262 - Survey Af-Am Lit Since 1900": null,
"AAS267W - The Civil Rights Movement": null,
"AAS272 - Race, Gender & Visual Repres": null,
"AAS279 - Intro.to African American Art": null,
"AAS306 - Music of Harlem Renaissance": null,
"AAS379 - African American Art": null,
"AAS388 - Topics": null,
"AAS482 - Black Women Writers": null,
"AAS483W - Reading Alice Walker": null,
"AAS490RW - Senior Seminar": null,
"AAS495BW - Honors Thesis": null,
"AFS280R - Anthro. Perspectives": null,
"AFS302W - Luso-African Texts & Cultures": null,
"AFS367 - The Making of South Africa": null,
"AFS495BW - African Studies Honors": null,
"AFS498R - Supervised Reading": null,
"AMST285 - Spec Top": null,
"AMST385W - Special Top": null,
"AMST388 - Topics": null,
"ANCMED201R - Mediterranean Archaeology": null,
"ANCMED495A - Honors Independent Writing": null,
"ANT202 - Concepts & Meth in Cult Anth": null,
"ANT231 - Predictive Health and Society": null,
"ANT302 - Primate Behavior & Ecology": null,
"ANT305 - The Human Brain": null,
"ANT314 - Race&Racism": null,
"ANT331 - Cross-Cult Iss in Mental Hlth": null,
"ANT363 - Ritual": null,
"ANT369W - Anthropology of Death & Burial": null,
"ANT385W - Special Topics": null,
"ANT397R - Directed Readings": null,
"ANT495BW - Honors Research II": null,
"ARAB102 - Elementary Arabic II": null,
"ARAB202 - Intermediate Arabic II": null,
"ARAB302 - Advanced Arabic II": null,
"ARAB402W - Advanced-Plus Arabic II": null,
"ARTHIST102 - Art/Arch Renaiss To Present": null,
"ARTHIST221 - Art&Architecture of Anc.Greece": null,
"ARTHIST233 - Introducing Medieval Buildings": null,
"ARTHIST242 - Italian Renaissance Art/Arch.": null,
"ARTHIST266 - Contemp Europe and America": null,
"ARTHIST279 - Intro.to African American Art": null,
"ARTHIST282 - Arts of Africa": null,
"ARTHIST329 - Topics": null,
"ARTHIST480RW - Sem": null,
"ARTHIST485 - Sem": null,
"ARTVIS112 - Foundations in Art PracticesII": null,
"ARTVIS205 - Intermediate Painting": null,
"ARTVIS305 - Painting Tutorial": null,
"BIOL142 - Foundations of Modern Biol II": null,
"BIOL142L - Found. of Modern Biol II Lab": null,
"BIOL212 - Comp.Model.Scient.& Engineers": null,
"BIOL325 - Primate Social Psychology": null,
"BIOL329 - Coastal Biology with Lab": null,
"BIOL355 - Intr. to Time Series Analysis": null,
"BIOL371 - Ecology of the Tropics": null,
"BIOL372 - Ecology of the Tropics Field": null,
"BIOL430 - Human Genome Project & Disease": null,
"BIOL450 - Computational Neuroscience": null,
"BIOL475 - Biology Of The Eye": null,
"BUS999XFR - Non-Equivalent Transfer Course": null,
"CBSC370B - Planning Community Initiatives": null,
"CBSC370L - Planning Comm.Initiatives-Lab": null,
"CHEM142 - General Chemistry II W/Lab": null,
"CHEM222 - Organic Chemistry II": null,
"CHEM222L - Organic Chemistry Laboratory 2": null,
"CHEM222Z - Organic Chemistry II": null,
"CHEM227L - Organic Chemistry Lab II": null,
"CHEM302 - Biochemistry II": null,
"CHEM328 - Intro.to Atmospheric Chemistry": null,
"CHEM332 - Physical Chemistry II": null,
"CHEM332LW - Physical Chemistry Lab II": null,
"CHEM470 - Special Topics in Chemistry": null,
"CHN102 - Elementary Chinese II": null,
"CHN202 - Intermediate Chinese II": null,
"CHN203 - Chinese for Heritge Speakrs II": null,
"CHN272 - Lit.in Early & Imperial China": null,
"CHN279W - Post-Mao? China After 1976": null,
"CHN302 - Adv Chinese II": null,
"CHN350W - East Asian Martial Arts": null,
"CHN368 - Writing Women in Trad China": null,
"CHN394W - Screening China": null,
"CHN402W - Adv Readings in Modern Chn II": null,
"CHN403W - Adv.High CHN for Heritage Spkr": null,
"CHN495BW - Honors Chinese": null,
"CL102 - Classical Mythology": null,
"CL150 - Masterworks of Classical Lit": null,
"CL214 - Ancient Drama": null,
"CL221 - Art&Architecture of Anc.Greece": null,
"CL309 - Warfare in Classical Culture": null,
"CL317W - Vergil and Dante": null,
"CL325W - Classical Trad & Amer Founding": null,
"CPLT110 - Intro to Literary Studies": null,
"CPLT302 - Literary Theory": null,
"CPLT317W - Vergil and Dante": null,
"CPLT489 - Advanced Special Topics": null,
"CPLT489W - Advanced Special Topics": null,
"CS285 - Topics in Computer Science": null,
"CS355 - Computer Architecture": null,
"CS378 - Data Mining": null,
"CS424 - Theory of Computing": null,
"CS452 - Operating Systems": null,
"CS495R - Honors": null,
"CS495RW - Honors": null,
"DANC211 - Tango": null,
"DANC220 - Hist.of Western Concert Dance": null,
"DANC229 - Introduction to Dance": null,
"DANC240 - Dance Literacy": null,
"DANC350 - Choreography II": null,
"DANC360R - Choreographic Laboratory": null,
"DANC385 - Spec Topics": null,
"DANC495B - Honors Thesis": null,
"EAS270 - Intro to Japanese Culture": null,
"EAS275 - Nature and Culture in Japan": null,
"EAS277 - Political Change in Korea": null,
"EAS279W - Post-Mao? China After 1976": null,
"EAS322 - Politics of Southeast Asia": null,
"EAS350W - East Asian Martial Arts": null,
"EAS368 - Writing Women in Trad.China": null,
"EAS372 - History of Modern Japan": null,
"EAS379 - History of Modern China": null,
"EAS382 - Two Koreas": null,
"EAS385W - Spec Top": null,
"EAS394W - Screening China": null,
"EAS451RW - Great Writers of Modern Japan": null,
"ECON362 - Economic Development": null,
"ECON385 - Special Topics in Economics": null,
"ECON385W - Special Topics in Economics": null,
"ECON394 - Washington Econ Policy Semestr": null,
"ECON397R - Directed Reading In Economics": null,
"ECON411 - Money & Banking": null,
"ECON421 - Microeconometrics": null,
"ECON422W - Economic Forecasting": null,
"ECON423 - Financial Econometrics": null,
"ECON442 - Law and Economics": null,
"ECS491 - Ethics and Leadership": null,
"EDS305 - History of American Education": null,
"EDS471R - Foundation Seminar": null,
"EDS471RW - Foundation Seminar": null,
"EDS472R - Curriculum Seminar": null,
"EDS497R - Directed Study": null,
"ENG150 - Great Works of Literature": null,
"ENG212W - Readings in Pop Lit/Culture": null,
"ENG216 - History of Drama & Theater II": null,
"ENG220W - Rhetorical Studies": null,
"ENG256W - British Literature Since 1660": null,
"ENG304W - Chaucer": null,
"ENG308W - Arthurian Literature": null,
"ENG315W - Renaiss Literature": null,
"ENG325W - The Early English Novel": null,
"ENG328W - Race, Gender, and Media-Making": null,
"ENG336W - The English Victorian Novel": null,
"ENG368W - Literature & Cultural Studies": null,
"ENG383RW - Studies In Women's Fiction": null,
"ENG386W - Literature and Science": null,
"ENG396R - Internship in English": null,
"ENG399RW - Independent Study": null,
"ENG480R - Seminar in Poetry": null,
"ENG489W - Special Top Adv Study": null,
"ENGCW271 - Introduction to Poetry Writing": null,
"ENGCW373RW - Creative Writing": null,
"ENGCW374RW - Creative Writing": null,
"ENGCW375RW - Creative Writing": null,
"ENGCW379W - Creative Writing": null,
"ENVS125 - Ecology, Geology & Nature Obs.": null,
"ENVS225 - Institutions & The Environment": null,
"ENVS229 - Atmospheric Science with Lab": null,
"ENVS235 - Environmental Geology": null,
"ENVS239 - Physical Oceanography": null,
"ENVS240 - Ecosystem Ecology": null,
"ENVS260 - Quantitative Methods in Environmental Science": null,
"ENVS275 - Nature and Culture in Japan": null,
"ENVS328 - Intro.to Atmospheric Chemistry": null,
"ENVS330 - Climatology": null,
"ENVS342 - Barrier Island": null,
"ENVS348 - Sustainable Water Res.with Lab": null,
"ENVS350W - Env Thgt": null,
"ENVS352W - Green Business": null,
"ENVS370B - Planning Community Initiatives": null,
"ENVS370L - Planning Comm.Initiatives-Lab": null,
"ENVS371 - Ecology of the Tropics": null,
"ENVS372 - Ecology of the Tropics Field": null,
"ENVS385 - Topics": null,
"ENVS420 - Law and Biodiversity": null,
"ENVS491 - Svc Learning Course In Envs": null,
"ENVS495BW - Honors Research": null,
"ENVS499R - Advanced Independent Research": null,
"FILM356 - History Of American Television": null,
"FILM372 - History Of Film Since 1954": null,
"FILM373W - Special Topics in Film": null,
"FILM374 - Animation": null,
"FILM377 - Narrative Filmmaking II": null,
"FILM382 - Contemp. Film & Media Theory": null,
"FILM389 - Special Topics in Media": null,
"FILM392R - Genre Studies": null,
"FILM394W - Screening China": null,
"FILM395R - National Cinemas": null,
"FILM396R - Non-Western National Cinemas": null,
"FILM406 - Senior Seminar in Film & Media": null,
"FILM407 - Content Creation": null,
"FREN190 - Freshman Seminar": null,
"FREN351 - Media and Genres": null,
"GER102 - Elementary German II": null,
"GER202 - Intermediate German II": null,
"GER302W - German Studies II": null,
"GER318 - Modern Germany": null,
"GER321 - Business German II": null,
"GER340 - German Film (in English)": null,
"GER470 - Topics": null,
"GER497R - Directed Study": null,
"GRK102 - Elementary Greek II": null,
"GRK110 - Intensive Elementary Greek": null,
"GRK202 - Intermediate Greek": null,
"GRK370 - Spec Topics": null,
"GRK495R - Honors": null,
"HEBR102 - Elementary Modern Hebrew II": null,
"HEBR202 - Intermediate Modern Hebrew II": null,
"HEBR302 - Advanced Modern Hebrew II": null,
"HIST202 - The Making of Modern Europe": null,
"HIST211 - Latin America": null,
"HIST215 - History of the American West": null,
"HIST231 - Found of American Society to 1877": null,
"HIST239W - Hist.of Afric.Amer. Since 1865": null,
"HIST241 - Topics in History and Text": null,
"HIST267W - The Civil Rights Movement": null,
"HIST279W - Post-Mao? China After 1976": null,
"HIST311 - Euro Nuclear Age": null,
"HIST318 - Modern Germany": null,
"HIST322 - Herod the Great": null,
"HIST325W - Classical Trad & Amer Founding": null,
"HIST332W - Gandhi": null,
"HIST341 - Era of the American Revolution": null,
"HIST347 - The Industrial Revolution": null,
"HIST350W - East Asian Martial Arts": null,
"HIST351 - Topics": null,
"HIST354 - US Legal & Constitutional Hist": null,
"HIST361 - Brazil": null,
"HIST367 - The Making of South Africa": null,
"HIST372 - History of Modern Japan": null,
"HIST373 - History of Modern China": null,
"HIST495BW - Intro Historcl Interpret II": null,
"HIST497 - Directed Research": null,
"HIST497W - Directed Research": null,
"HLTH200 - Peer Health Training": null,
"HLTH210 - Predictive Health and Society": null,
"HLTH221 - Contemporary Nutrition": null,
"HLTH321 - Nutrition Across Life Cycle": null,
"HLTH385W - Special Topics": null,
"HLTH411 - Many Diseases, Few Causes": null,
"HLTH415 - Future Health": null,
"HLTH420 - Mythbusters": null,
"HLTH495BW - Honors Research": null,
"HNDI102 - Elementary Hindi II": null,
"HNDI202 - Intermediate Hindi II": null,
"IDS205W - Science&the Nature of Evidence": null,
"IDS285W - Intro.Interdisciplinary Topics": null,
"IDS390 - Interdisciplinary Std Tutorial": null,
"IDS391 - Sustainability CapstoneSeminar": null,
"IDS392 - Capstone Development Studies": null,
"ITAL102 - Language & Culture, Elem. II": null,
"ITAL202 - Language & Culture, Inter. II": null,
"ITAL302W - Language & Culture; Adv. II": null,
"ITAL317W - Vergil and Dante": null,
"ITAL497R - Individual Directed Study": null,
"JPN102 - Elementary Japanese II": null,
"JPN202 - Intermediate Japanese II": null,
"JPN232 - Lang Usage in Japanese Society": null,
"JPN270 - Intro to Japanese Culture": null,
"JPN275 - Nature and Culture in Japan": null,
"JPN302W - Adv Conv & Composition II": null,
"JPN402 - Adv Lang & Cultural Studies II": null,
"JPN451RW - Great Writers of Modern Japan": null,
"JS210R - Classic Religious Texts": null,
"JS252 - The Archaeology of Jerusalem": null,
"JS275 - Topics in Jewish Literature": null,
"JS308 - Judaism": null,
"JS322 - Herod the Great": null,
"JS343 - Modern Jewish Thought": null,
"JS370 - Top In Jewish Relig & Culture": null,
"JS375W - Topics In Jewish Literature": null,
"JS490R - Sen Seminar In Jewish Studies": null,
"JS490RW - Sen Seminar In Jewish Studies": null,
"KRN202 - Intermediate Korean II": null,
"KRN271 - Political Change in Korea": null,
"KRN302 - Advanced Korean II": null,
"KRN382 - Two Koreas": null,
"KRN397R - Korean Directed Study": null,
"KRN402 - Language & Culture of Korea II": null,
"KRN404 - Topics": null,
"LACS265W - Visitor Meets Native": null,
"LACS363W - Sugar and Rum": null,
"LACS385 - Sp Top": null,
"LACS497R - Independent Study": null,
"LAT102 - Elementary Latin II": null,
"LAT202 - Intermediate Latin": null,
"LAT290R - Supervised Reading": null,
"LAT315 - Comedy": null,
"LING101 - Hist of the American Languages": null,
"LING210 - Sounds of Human Language": null,
"LING318 - Second Language Acquisition": null,
"LING340 - Topics in Sociolinguistics": null,
"LING383 - Advertising": null,
"LING385W - Special Topics in Linguistics": null,
"LING401W - Language, Mind & Society": null,
"LING485 - Advanced Topics in Linguistics": null,
"LING495BW - Honors Directed Research": null,
"MATH190 - Fresh Sem": null,
"MATH276 - Honors Vector Calculus": null,
"MATH297 - Directed Study": null,
"MATH321 - Abstract Vector Spaces": null,
"MATH330 - Intro To Combinatorics": null,
"MATH344 - Differential Geometry": null,
"MATH362 - Probability And Statistics II": null,
"MATH362W - Probability and Statistics II": null,
"MATH412 - Real Analysis II": null,
"MATH422 - Abstract Algebra II": null,
"MATH495R - Honors": null,
"MESAS200W - Interpreting The Middle East": null,
"MESAS201W - Reading the Middle East": null,
"MESAS202W - South Asian History & Identity": null,
"MESAS205R - Music Traditions of South Asia": null,
"MESAS252 - The Archaeology of Jerusalem": null,
"MESAS255 - Top": null,
"MESAS322 - Herod the Great": null,
"MESAS332W - Gandhi": null,
"MESAS338 - Tibetan History": null,
"MESAS414W - Shiite Islam": null,
"MESAS470 - Special Topics in MESAS": null,
"MESAS490W - Senior Seminar in MESAS": null,
"MESAS495RW - Honors Seminar in MESAS": null,
"MUS122 - Theory & Analysis II W/ Lab": null,
"MUS211 - Tango": null,
"MUS245 - Jazz Theory & Analysis": null,
"MUS281 - Baroque Music": null,
"MUS284 - Music & Contemporary Society": null,
"MUS306 - Music of Harlem Renaissance": null,
"MUS315 - Conducting": null,
"MUS340 - Jazz Improv II": null,
"MUS367 - Computer Music Composition": null,
"MUS370W - Special Topics": null,
"MUS390R - Half - Recital": null,
"MUS441 - Diction for Singers II": null,
"MUS470W - Special Topics Seminar": null,
"MUS490R - Full - Recital": null,
"MUS495B - Honors": null,
"MUS495BW - Honors": null,
"NBB299 - Explore NBB Research": null,
"NBB321 - Behavrl Neuroendocrinology": null,
"NBB361W - Neurophysiology Laboratory": null,
"NBB424 - Medical Neuropathology": null,
"NRSG304 - Assessment Hormone Form &Func": null,
"NRSG315 - Population Health": null,
"NRSG324 - Case Study Analysis Seminar I": null,
"NRSG332 - Scholarly Inquiry": null,
"NRSG371 - Evidence Based Nrsg Practice": null,
"NRSG385 - Nursing Elective": null,
"NRSG389 - The Science & Culture of Sleep": null,
"NRSG412 - Nursing Care-Oncology Patient": null,
"NRSG446 - Capstone for Public Health": null,
"NRSG452 - Frontline": null,
"NRSG454 - Honors Thesis II": null,
"NRSG480 - Int.Healthc.Syst": null,
"NRSG482 - Birth and Global Health": null,
"NRSG483 - Perioperative Nursing": null,
"NRSG497R - Directed Study": null,
"PE181 - Conditioning/Racquetball": null,
"PE194 - Stress Reduction & Flexibility": null,
"PE214 - Conditioning/Jogging": null,
"PE273 - Intermediate Tennis": null,
"PE291 - Intermediate Social Dance": null,
"PE356 - Lifeguard Training": null,
"PE402R - PPF": null,
"PE405R - PPF": null,
"PE406R - PPF": null,
"PE407R - PPF": null,
"PE408R - PPF": null,
"PE409R - PPF": null,
"PE411R - PPF": null,
"PE412R - PPF": null,
"PE413R - PPF": null,
"PERS102 - Elementary Persian II": null,
"PERS202 - Intermediate Persian II": null,
"PERS302W - Advanced Persian II": null,
"PHIL124 - Philosophy of Race & Ethnicity": null,
"PHIL126 - Mind, Brain, Self & Evolution": null,
"PHIL128 - Metaphysics& Nature of Reality": null,
"PHIL130 - Intro Philosophy & Literature": null,
"PHIL321 - Philosophy of Law": null,
"PHIL412 - Pragmatism": null,
"PHIL420 - Social & Political Philosophy": null,
"PHIL430 - Philosophy of Literature": null,
"PHYS121 - How Things Work": null,
"PHYS142 - Intro Physics II W/Lab": null,
"PHYS152 - Phys for Sci & Engin II W/Lab": null,
"PHYS212 - Comp.Model.Scient.& Engineers": null,
"PHYS222 - Fund. of Engineering Design": null,
"PHYS227 - Seminar in Modern Med Physics": null,
"PHYS312 - Astrophysics II with Lab": null,
"PHYS333 - Physics for Life Sciences": null,
"PHYS361 - Classical Mechanics": null,
"PHYS421 - Thermodynamics & Stat Phys": null,
"PHYS432 - Principles of Optics With Lab": null,
"PHYS461 - Quantum Mechanics": null,
"POLS200 - Intermed Natl Politics of U.S.": null,
"POLS210 - Interm. International Politics": null,
"POLS220 - Intermed. Comparative Politics": null,
"POLS319 - Intl Political Economy": null,
"POLS322 - Politics of Southeast Asia": null,
"POLS326 - Western European Politics": null,
"POLS342 - Congressional Politics": null,
"POLS345 - American Political Parties": null,
"POLS353 - Civil Liberties": null,
"POLS369 - Public Policy Analysis": null,
"POLS370B - Planning Community Initiatives": null,
"POLS370L - Planning Comm.Initiatives-Lab": null,
"POLS371 - Guerilla Political Videography": null,
"POLS374W - Research": null,
"POLS494 - Rsch Topics Sem Polit Science": null,
"POLS499 - Honors Research": null,
"PORT102 - Elementary Portuguese II": null,
"PORT212 - Adv Practice in Portuguese": null,
"PORT302W - Luso-African Texts & Cultures": null,
"PORT385 - Topics": null,
"PSYC103 - Brain & Behavior": null,
"PSYC215 - Cognition": null,
"PSYC218 - Infancy": null,
"PSYC321 - Behavrl Neuroendocrinology": null,
"PSYC325 - Primate Social Psychology": null,
"PSYC350 - Behavior Modification": null,
"PSYC385W - Special Topics in Psychology": null,
"PSYC430 - Adv Statistics & Res. Methods": null,
"PSYC450 - The Psychology of Love": null,
"PSYC475R - Sem": null,
"PSYC476R - Biolog Foundations of Behavior": null,
"PSYC495BW - Honors Program": null,
"QTM345 - Advanced Statistics": null,
"QTM355 - Intr. to Time Series Analysis": null,
"QTM496R - Quantitative Sci. Internship": null,
"REES375 - Special Topics": null,
"REES375W - Special Topics": null,
"REES497R - Directed Study": null,
"REL200R - Relig & Contemp Experience": null,
"REL210R - Classic Religious Texts": null,
"REL305 - Introduction to Buddhism": null,
"REL308 - Judaism": null,
"REL310R - Modern Buddhism": null,
"REL313W - Modern Catholicism": null,
"REL338 - Tibetan History": null,
"REL343 - Modern Jewish Thought": null,
"REL348W - New Testament in its Context": null,
"REL352R - Gender and Religion": null,
"REL358RW - Religion and Healing": null,
"REL369R - Religion, Film & Media": null,
"REL414W - Shiite Islam": null,
"REL490W - Snr Symposium": null,
"REL495RW - Directed Reading (Honors)": null,
"RUSS102 - Elementary Russian II": null,
"RUSS202 - Inter Composition/Conversation": null,
"RUSS270W - Russian Culture": null,
"RUSS411 - Contemp.Readings & Translatn I": null,
"RUSS420 - Philosophy&Religion in Russia": null,
"RUSS495BW - Honors Program In Russian": null,
"SOC220 - Juvenile Delinquency": null,
"SOC271 - Political Change in Korea": null,
"SOC289W - Special Topics in Sociology": null,
"SOC330 - Mental Health and Well-Being": null,
"SOC333 - Sociology of Religion": null,
"SOC350 - Sociology of Law": null,
"SOC370B - Planning Community Initiatives": null,
"SOC370L - Planning Comm.Initiatives-Lab": null,
"SOC383 - Advertising": null,
"SOC443 - Senior Sem": null,
"SOC489 - Special Topics in Sociology": null,
"SOC495BW - Honors": null,
"SPAN102 - Elementary Spanish II": null,
"SPAN111 - Intensive Spanish": null,
"SPAN202 - Intermediate Spanish II": null,
"SPAN217R - Spanish for the Professions": null,
"SPAN311 - Hispanic Narrative": null,
"SPAN312 - Theater, Film & Performing Art": null,
"SPAN330 - Theater Workshop in Spanish": null,
"SPAN385W - Topics in Language and Culture": null,
"SPAN440W - Topics in Colonial Studies": null,
"SPAN450 - Topics": null,
"SPAN495BW - Honors": null,
"SPAN497R - Supervised Reading": null,
"TBT102 - Elementary Tibetan II": null,
"THEA216 - History of Drama & Theater II": null,
"THEA230 - Principles Of Design": null,
"THEA240 - Arts Administration": null,
"THEA270R - Experiencing New Works": null,
"THEA322 - Acting": null,
"THEA326 - Acting for the Camera": null,
"THEA331 - Costume Design": null,
"THEA375RW - Advanced Playwriting": null,
"THEA389W - Special Topics": null,
"THEA396R - Theater Colloquia": null,
"THEA419R - Dramaturgy Tutorial": null,
"THEA494RW - Honors in Playwriting": null,
"WGS205W - Intro Study in Sexualities": null,
"WGS285W - Variable Topics in WGSS": null,
"WGS300 - Feminist Theory": null,
"WGS302 - Contemporary Feminist Theory": null,
"WGS352R - Gender and Religion": null,
"WGS368 - Writing Women in Trad.China": null,
"WGS475R - Advanced Seminar": null,
"WGS483W - Reading Alice Walker": null,
"AAS239 - Hist.of Afric.Amer. Since 1865": null,
"AAS262W - Survey Af-Am Lit Since 1900": null,
"AAS304 - Music & Revolution in 1960s": null,
"AAS306W - Music of Harlem Renaissance": null,
"AAS320R - African - American Religion": null,
"AAS346 - African American Politics": null,
"AAS350 - African American Pedagogy": null,
"AAS359 - Studies AF/AM Lit.1900-Present": null,
"AAS388 - Race, Gender, & the South": null,
"AAS490R - Senior Seminar": null,
"AFS221 - The Making of Modern Africa": null,
"AFS282 - Arts of Africa": null,
"AMST321 - American Routes": null,
"ANCMED495BW - Honors Independent Writing": null,
"ANT210 - Hum Biol": null,
"ANT230 - Medical Anthropology": null,
"ANT252 - Fast Food/Slow Food": null,
"ANT285W - Anthropology; Special Topics": null,
"ANT307W - Human Evolution": null,
"ANT319 - Anthropology of Fatherhood": null,
"ANT333 - Disease & Human Behavior": null,
"ANT391 - Law, Discipline, & Social Justice": null,
"ARTHIST226 - Anc't South & Central Amer Art": null,
"ARTHIST339R - Spec Stud": null,
"ARTHIST359R - Spec Stud": null,
"ARTHIST470R - Sem": null,
"ARTVIS333R - Multidiscipline Design Studio": null,
"ARTVIS495RW - Honors": null,
"BIOL347 - Disease Ecology": null,
"BIOL415 - Cancer Biology And Oncogenes": null,
"BIOL440W - Animal Communication": null,
"CHEM202 - Principles of Reactivity": null,
"CHEM202L - Principles of Reactivity Lab": null,
"CHEM332L - Physical Chemistry Lab II": null,
"CHEM495R - Honors Thesis": null,
"CHN190 - Freshman Seminar": null,
"CHN203 - Interm.CHN for Heritage Spkrs": null,
"CHN272W - Lit. in Early & Imperial China": null,
"CHN368 - Writing Women in Trad.China": null,
"CHN394 - Screening China": null,
"CL103 - Greek Archaeology": null,
"CL203 - Greeks & Romans By Hollywood": null,
"CL215 - Greek and Roman Religion": null,
"CL329RW - Spec Stud in Classical Culture": null,
"CL487 - Special Topics in Classics": null,
"CL495RW - Honors Course": null,
"CS385 - Topics in Computer Science": null,
"CS425 - Artificial Intelligence": null,
"CS455 - Intro to Computer Networking": null,
"DANC424R - Jazz IV": null,
"EAS212 - Asian Religious Traditions": null,
"EAS272W - Lit. in Early & Imperial China": null,
"EAS361 - Genji": null,
"EAS394 - Screening China": null,
"EAS450W - Seminar in East Asian Studies": null,
"ECON315 - Economics and Psychology": null,
"ECON356 - Devlpmnt Of Mod U.S. Economy": null,
"ECON365 - Environ Economics And Policy": null,
"ECON487 - Game Theory & Econ. Activity": null,
"ECON490R - Advanced Seminar": null,
"ECON495A - Honors Seminar": null,
"ENG213W - Fictions of Human Desire": null,
"ENG214W - Global Literature In English": null,
"ENG251 - American Lit": null,
"ENG251W - American Lit": null,
"ENG258 - Introduction to Irish Studies": null,
"ENG359 - Studies AF/AM Lit.1900-Present": null,
"ENG360W - The English Language": null,
"ENG384R - Criticism": null,
"ENG412RW - Sem": null,
"ENG496R - Internship In English": null,
"ENGCW379 - Creative Writing": null,
"ENVS230 - Introductory Geoscience with Lab": null,
"ENVS241 - Mod & Anc Trop Environments": null,
"ENVS242 - Mod & Anc Trop Env Field Crs": null,
"ENVS260 - Quant Tech in Environ Stdy": null,
"ENVS285W - Special Topics": null,
"ENVS331 - Earth Systems Science": null,
"ENVS347 - Landscapes and Geomorphology": null,
"ENVS386 - Special Topics w/Lab": null,
"ENVS483 - Spatial Analys.in Disease Ecol": null,
"FILM383W - Music, Film, and Politics": null,
"FILM394 - Screening China": null,
"FREN391R - Francophone Studies": null,
"FREN495BW - Honors": null,
"GER380 - Topics in German Studies": null,
"GER475W - Topics": null,
"HEBR370 - Topics in Hebrew": null,
"HIST221 - The Making of Modern Africa": null,
"HIST232 - Making of Mod Am": null,
"HIST239 - Hist.of Afric.Amer. Since 1865": null,
"HIST301 - Greek World": null,
"HIST306 - The Italian Renaissance": null,
"HIST320W - The Soviet Union": null,
"HIST324 - Age of Religious Wars": null,
"HIST359 - American Music": null,
"HIST377W - Euro Intellectual History/1880": null,
"HIST383 - The Arab-Israeli Conflict": null,
"HIST386 - Seminar on the Holocaust": null,
"HLTH340 - Food, Health, and Society": null,
"IDS250 - Ethics of Leadership": null,
"IDS385 - SThe Science, Medicine, and Ethics of Killingpecial Topics": null,
"IDS385W - House (M.D.) and Holmes": null,
"IDS489W - Advanced Special Topics": null,
"JPN361 - Genji": null,
"JS101 - Introduction to Jewish Studies": null,
"JS273W - Topics in Jewish Rel & Culture": null,
"JS324 - The Holocaust": null,
"JS341 - Medieval Jewish Thought": null,
"JS354RW - Ethics": null,
"JS383 - The Arab-Israeli Conflict": null,
"JS470 - Topics in Jewish Rel. & Cult.": null,
"LACS190 - Fr Sem": null,
"LACS270 - Topics": null,
"LAT110 - Intensive Latin": null,
"LAT320 - Medieval Latin": null,
"LAT495RW - Honors": null,
"LING214 - Meaning in Human Language": null,
"LING285 - Intro Topics in Linguistics": null,
"LING316 - Language Acquisition": null,
"LING360W - The English Language": null,
"MATH352 - PDE's in Action": null,
"MATH362 - Probability and Statistics II": null,
"MESAS200W - Middle Eastern Civilization": null,
"MESAS202W - South Asian Civilizations": null,
"MESAS355 - The Great Decipherments": null,
"MESAS375W - Topics In Jewish Literature": null,
"MUS190 - Wrap Your Troubles in Dreams": null,
"MUS222 - Theory and Analysis IV": null,
"MUS282 - Haydn, Mozart, & Beethoven": null,
"MUS304 - Music & Revolution in 1960s": null,
"MUS306W - Music of Harlem Renaissance": null,
"MUS365W - Wagner and Wagnerism": null,
"MUS370 - Composition Seminar": null,
"MUS370 - Special Topics": null,
"MUS383W - Music, Film, and Politics": null,
"MUS445 - Arranging & Orchestration": null,
"MUS463 - Popular Music Cultures of China, Hong Kong, and Taiwan": null,
"MUS470W - Music and Scripture": null,
"NBB270 - Special Topics in NBB": null,
"NBB319 - Anthropology of Fatherhood": null,
"NBB426 - Neuropharmacology & Placebo": null,
"NBB470 - Special Topics in NBB": null,
"PE292 - Intermediate Fencing": null,
"PHIL125 - Intro to Philosophy of Science": null,
"PHIL131 - Intro Philosophy of Religion": null,
"PHIL202 - Renaissance &Modern Philosophy": null,
"PHIL220W - History of Political Phil.": null,
"PHIL311 - Existentialism & Phenomenology": null,
"PHIL335 - Marx and Marxism": null,
"PHIL385 - Special Topics": null,
"PHIL400 - Topic Ancient Greek Philosophy": null,
"PHIL411 - Phenomenology": null,
"PHIL482W - Topics": null,
"PHYS117 - Intr. Astronomy 2": null,
"PHYS311 - Astrophysics I with Laboratory": null,
"POLS102 - Intro to Political Theory": null,
"POLS313W - Rch": null,
"POLS319 - Int'l Political Economy": null,
"POLS325 - Eastern European Politics": null,
"POLS346 - African American Politics": null,
"POLS354 - Criminal Justice": null,
"POLS355 - Nonprofits and Politics": null,
"POLS383 - The Arab-Israeli Conflict": null,
"PORT301W - Portuguese Texts and Cultures": null,
"PSYC150 - Great Works in Psychology": null,
"PSYC316 - Language Acquisition": null,
"PSYC322 - Biolog Basis/Learning & Memory": null,
"PSYC420W - Psychobio of Visual Perception": null,
"PSYC424 - Advanced Neuroimaging Practicum": null,
"PSYC440W - Animal Communication": null,
"QTM110 - Intro to Scientific Methods": null,
"QTM120 - Math for Quantitative Sciences": null,
"QTM150 - Intro to Stat Computing I": null,
"QTM151 - Intro to Stat Computing II": null,
"QTM355 - Intr to Time Series Analysis": null,
"QTM491 - Design / Analysis Experiments": null,
"QTM495BW - Honors Research": null,
"REES190 - Fresh Sem": null,
"REES200W - Intro to Russian Area Studies": null,
"REL215 - Greek and Roman Religion": null,
"REL270W - Special Topics in Religion": null,
"REL320R - African - American Religion": null,
"REL324 - The Holocaust": null,
"REL341 - Medieval Jewish Thought": null,
"REL350W - Jesus and the Gospels": null,
"REL370W - Special Topics in Religion": null,
"REL373 - Spec Tops": null,
"REL387W - Literature & Religion": null,
"RUSS271W - Imperial Russian Culture": null,
"RUSS311 - Fict & Nonfiction In Russian": null,
"SOC213 - Sociology of the Family": null,
"SOC249 - Criminology": null,
"SOC307 - Sociology of Education": null,
"SOC343 - Mass Media & Social Influences": null,
"SOC347 - Gender and Global Health": null,
"SOC356 - Social Research II": null,
"SOC494R - Internship in Sociology": null,
"SPAN150 - Great Works": null,
"THEA289 - Special Topics": null,
"THEA366 - Comtemporary Drama": null,
"THEA370R - Creating New Works": null,
"THEA495RW - Honors Project in Theater": null,
"THEA496R - Internship in Theater": null,
"WGS285W - Variable Topics": null,
"WGS312 - User's Guide to Freud": null,
"WGS347 - Gender and Global Health": null
            },
           // limit: 20, // The max amount of results that can be shown at once. Default: Infinity.
            onAutocomplete: function(val) {
              // Callback function when value is autcompleted.
            var url = '/search?q='+val;
           window.location.href =url;

            },
            minLength: 1, // The minimum length of the input for the autocomplete to start. Default: 1.
          });
        });
  }

  render() {
    console.log(this.props.search);
    if(this.props.search)
    {
      var icon="material-icons inputIconOverride2";
      var height="36px";
    }
    else
    {
      var icon="material-icons inputIconOverride";
      var height="inherit"
    }
    return (
      <div className="input-field" style={{height: "54px", lineHeight:"40px"}}>
        <input
          id="search"
          type="search"
          className="autocomplete"
          placeholder="Search for a course"
          required
          autoComplete ="off"
          value={this.state.inputValue.bind} 
          onChange={this.updateInputValue}
          onKeyPress={this._handleKeyPress}
          style={{marginTop:10, height:height, backgroundColor:"#eeeeee", borderRadius:30}}
        />
        <label
          className="label-icon hide-on-small-only inputOverride"
          htmlFor="search" 
        >
          <i
            className={icon} style={{lineHeight: "54px"}}
          >
            search
          </i>
        </label>
        <label
          className="label-icon hide-on-med-and-up inputOverride"
          htmlFor="search" 
        >
          <i
            className={icon} style={{lineHeight: "54px", bottom:20, paddingLeft: 10}}
          >
            search
          </i>
        </label>
        
      </div>
    );
  }
}
const mapStateToProps = (state) => {
  return{
    state
  }
}

const mapDispatchToProps = (dispatch) => {
  return {
  }
}

export default withRouter(connect(
  mapStateToProps,
  mapDispatchToProps
)(Inputfield));
